-- Migration: V3__add_multi_warehouse_allocation.sql
-- Description: Creates warehouses, warehouse_inventories, order_item_warehouse_allocations tables, updates stock_movements, and seeds initial facilities.

-- 1. Create warehouses table
CREATE TABLE IF NOT EXISTS warehouses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(100) NOT NULL DEFAULT 'India',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_warehouses_code ON warehouses(warehouse_code);
CREATE INDEX IF NOT EXISTS idx_warehouses_active ON warehouses(active);
CREATE INDEX IF NOT EXISTS idx_warehouses_city ON warehouses(city);

-- 2. Create warehouse_inventories table
CREATE TABLE IF NOT EXISTS warehouse_inventories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    total_quantity INTEGER NOT NULL DEFAULT 0 CHECK (total_quantity >= 0),
    reserved_quantity INTEGER NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
    available_quantity INTEGER NOT NULL DEFAULT 0 CHECK (available_quantity >= 0),
    low_stock_threshold INTEGER NOT NULL DEFAULT 10 CHECK (low_stock_threshold >= 0),
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_warehouse_product UNIQUE (warehouse_id, product_id),
    CONSTRAINT fk_wh_inv_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE CASCADE,
    CONSTRAINT fk_wh_inv_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_wh_inv_warehouse_id ON warehouse_inventories(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_wh_inv_product_id ON warehouse_inventories(product_id);
CREATE INDEX IF NOT EXISTS idx_wh_inv_available ON warehouse_inventories(available_quantity);

-- 3. Create order_item_warehouse_allocations table
CREATE TABLE IF NOT EXISTS order_item_warehouse_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    warehouse_inventory_id BIGINT,
    allocated_quantity INTEGER NOT NULL CHECK (allocated_quantity > 0),
    allocation_status VARCHAR(50) NOT NULL DEFAULT 'ALLOCATED',
    allocated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    picked_at TIMESTAMP(6) WITHOUT TIME ZONE,
    packed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    ready_for_shipment_at TIMESTAMP(6) WITHOUT TIME ZONE,
    notes VARCHAR(500),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_alloc_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_alloc_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE CASCADE,
    CONSTRAINT fk_alloc_wh_inventory FOREIGN KEY (warehouse_inventory_id) REFERENCES warehouse_inventories(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_alloc_order_item_id ON order_item_warehouse_allocations(order_item_id);
CREATE INDEX IF NOT EXISTS idx_alloc_warehouse_id ON order_item_warehouse_allocations(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_alloc_status ON order_item_warehouse_allocations(allocation_status);

-- 4. Add optional warehouse_id column to stock_movements if not present
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'stock_movements' 
          AND column_name = 'warehouse_id'
    ) THEN
        ALTER TABLE stock_movements 
        ADD COLUMN warehouse_id BIGINT;

        ALTER TABLE stock_movements 
        ADD CONSTRAINT fk_stock_movements_warehouse 
        FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE SET NULL;

        CREATE INDEX idx_stock_movements_warehouse_id ON stock_movements(warehouse_id);
    END IF;
END $$;

-- 5. Seed initial physical warehouses
INSERT INTO warehouses (warehouse_code, name, address, city, state, postal_code, country, active)
VALUES 
    ('WH-BLR-01', 'Bangalore Central Fulfillment Center', 'Electronic City Phase 1, Hosur Road', 'Bangalore', 'Karnataka', '560100', 'India', TRUE),
    ('WH-BOM-01', 'Mumbai Logistics & Cargo Depot', 'MIDC Industrial Area, Andheri East', 'Mumbai', 'Maharashtra', '400093', 'India', TRUE),
    ('WH-MAA-01', 'Chennai Coastal Distribution Hub', 'Grand Southern Trunk Road, Guindy', 'Chennai', 'Tamil Nadu', '600032', 'India', TRUE)
ON CONFLICT (warehouse_code) DO NOTHING;

-- 6. Populate warehouse_inventories for all existing products using primary warehouse (WH-BLR-01)
DO $$
DECLARE
    blr_wh_id BIGINT;
    r RECORD;
BEGIN
    SELECT id INTO blr_wh_id FROM warehouses WHERE warehouse_code = 'WH-BLR-01';
    
    IF blr_wh_id IS NOT NULL THEN
        FOR r IN 
            SELECT p.id as product_id, 
                   COALESCE(i.total_stock, p.stock_quantity, 100) as total_qty,
                   COALESCE(i.reserved_stock, 0) as reserved_qty,
                   COALESCE(i.available_stock, p.stock_quantity, 100) as avail_qty,
                   COALESCE(i.low_stock_threshold, 10) as threshold
            FROM products p
            LEFT JOIN inventories i ON p.id = i.product_id
        LOOP
            INSERT INTO warehouse_inventories (
                warehouse_id, product_id, total_quantity, reserved_quantity, available_quantity, low_stock_threshold, version
            )
            VALUES (
                blr_wh_id, r.product_id, r.total_qty, r.reserved_qty, r.avail_qty, r.threshold, 0
            )
            ON CONFLICT (warehouse_id, product_id) DO NOTHING;
        END LOOP;
    END IF;
END $$;
